export interface Types {
  Normal: boolean,
  Combat: boolean,
  Vol: boolean,
  Poison: boolean,
  Sol: boolean,
  Roche: boolean,
  Insecte: boolean,
  Spectre: boolean,
  Acier: boolean,
  Feu: boolean,
  Eau: boolean,
  Plante: boolean,
  Électrik: boolean,
  Psy: boolean,
  Glace: boolean,
  Dragon: boolean,
  Ténèbres: boolean,
  Fée: boolean,
}
